export type CountryOption = {
  label: string;
  value: string;
};

export const countryOptions: CountryOption[] = [
  { label: "UNITED STATES", value: "us" },
  { label: "UNITED KINGDOM", value: "gb" },
  { label: "UNITED ARAB EMIRATES", value: "ae" },
  { label: "AFGHANISTAN", value: "af" },
  { label: "ALBANIA", value: "al" },
  { label: "ALGERIA", value: "dz" },
  { label: "AMERICAN SAMOA", value: "as" },
  { label: "ANDORRA", value: "ad" },
  { label: "ANGOLA", value: "ao" },
  { label: "ANGUILLA", value: "ai" },
  { label: "ANTARCTICA", value: "aq" },
  { label: "ANTIGUA AND BARBUDA", value: "ag" },
  { label: "ARGENTINA", value: "ar" },
  { label: "ARMENIA", value: "am" },
  { label: "ARUBA", value: "aw" },
  { label: "AUSTRALIA", value: "au" },
  { label: "AUSTRIA", value: "at" },
  { label: "AZERBAIJAN", value: "az" },
  { label: "BAHAMAS", value: "bs" },
  { label: "BAHRAIN", value: "bh" },
  { label: "BANGLADESH", value: "bd" },
  { label: "BARBADOS", value: "bb" },
  { label: "BELARUS", value: "by" },
  { label: "BELGIUM", value: "be" },
  { label: "BELIZE", value: "bz" },
  { label: "BENIN", value: "bj" },
  { label: "BERMUDA", value: "bm" },
  { label: "BHUTAN", value: "bt" },
  { label: "BOLIVIA", value: "bo" },
  { label: "BOSNIA AND HERZEGOVINA", value: "ba" },
  { label: "BOTSWANA", value: "bw" },
  { label: "BOUVET ISLAND", value: "bv" },
  { label: "BRAZIL", value: "br" },
  { label: "BRITISH INDIAN OCEAN TERRITORY", value: "io" },
  { label: "BRUNEI DARUSSALAM", value: "bn" },
  { label: "BULGARIA", value: "bg" },
  { label: "BRUNEI", value: "bn" },
  { label: "BURKINA FASCO", value: "bf" },
  { label: "BURUNDI", value: "bi" },
  { label: "CAMBODIA", value: "kh" },
  { label: "CAMEROON", value: "cm" },
  { label: "CANADA", value: "ca" },
  { label: "CAPE VERDE", value: "cv" },
  { label: "CAYMAN ISLANDS", value: "ky" },
  { label: "CENTRAL AFRICAN REPUBLIC", value: "cf" },
  { label: "CHAD", value: "td" },
  { label: "CHILE", value: "cl" },
  { label: "CHINA", value: "cn" },
  { label: "CHRISTMAS ISLAND", value: "cx" },
  { label: "COLOMBIA", value: "co" },
  { label: "COMOROS", value: "km" },
  { label: "CONGO", value: "cg" },
  { label: "CONGO, THE DEMOCRATIC REPUBLIC OF THE", value: "cd" },
  { label: "COOK ISLANDS", value: "ck" },
  { label: "COSTA RICA", value: "cr" },
  { label: "DR CONGO", value: "cd" },
  { label: "COTE D IVOIRE", value: "ci" },
  { label: "IVORY COAST", value: "ci" },
  { label: "CROATIA", value: "hr" },
  { label: "JERSEY", value: "je" },
  { label: "CUBA", value: "cu" },
  { label: "CYPRUS", value: "cy" },
  { label: "CURAÇAO", value: "cw" },
  { label: "CZECH REPUBLIC", value: "cz" },
  { label: "DENMARK", value: "dk" },
  { label: "DJIBOUTI", value: "dj" },
  { label: "DOMINICA", value: "dm" },
  { label: "DOMINICAN REPUBLIC", value: "do" },
  { label: "EAST TIMOR", value: "tp" },
  { label: "ECUADOR", value: "ec" },
  { label: "EGYPT", value: "eg" },
  { label: "EL SALVADOR", value: "sv" },
  { label: "EQUATORIAL GUINEA", value: "gq" },
  { label: "ERITREA", value: "er" },
  { label: "ESTONIA", value: "ee" },
  { label: "ETHIOPIA", value: "et" },
  { label: "FALK", value: "fk" },
  { label: "FAROE ISLANDS", value: "fo" },
  { label: "FIJI", value: "fj" },
  { label: "FINLAND", value: "fi" },
  { label: "FRANCE", value: "fr" },
  { label: "FRENCH GUIANA", value: "gf" },
  { label: "FRENCH POLYNESIA", value: "pf" },
  { label: "FRENCH SOUTHERN TERRITORIES", value: "tf" },
  { label: "GABON", value: "ga" },
  { label: "GAMBIA", value: "gm" },
  { label: "GEORGIA", value: "ge" },
  { label: "GERMANY", value: "de" },
  { label: "GHANA", value: "gh" },
  { label: "GIBRALTAR", value: "gi" },
  { label: "GREECE", value: "gr" },
  { label: "GREENLAND", value: "gl" },
  { label: "GRENADA", value: "gd" },
  { label: "GUADELOUPE", value: "gp" },
  { label: "GUAM", value: "gu" },
  { label: "GUATEMALA", value: "gt" },
  { label: "GUINEA", value: "gn" },
  { label: "GUINEA-BISSAU", value: "gw" },
  { label: "GUYANA", value: "gy" },
  { label: "HAITI", value: "ht" },
  { label: "HEARD ISLAND AND MCDONALD ISLANDS", value: "hm" },
  { label: "HOLY", value: "va" },
  { label: "VATICAN", value: "va" },
  { label: "HONDURAS", value: "hn" },
  { label: "TIMOR", value: "tl" },
  { label: "TIMOR LESTE", value: "tl" },
  { label: "HONG KONG", value: "hk" },
  { label: "HUNGARY", value: "hu" },
  { label: "ICELAND", value: "is" },
  { label: "INDIA", value: "in" },
  { label: "INDONESIA", value: "id" },
  { label: "IRAN, ISLAMIC REPUBLIC OF", value: "ir" },
  { label: "IRAQ", value: "iq" },
  { label: "IRAN", value: "ir" },
  { label: "IRELAND", value: "ie" },
  { label: "ISRAEL", value: "il" },
  { label: "ITALY", value: "it" },
  { label: "JAMAICA", value: "jm" },
  { label: "JAPAN", value: "jp" },
  { label: "JORDAN", value: "jo" },
  { label: "KAZAKHSTAN", value: "kz" },
  { label: "KENYA", value: "ke" },
  { label: "KIRIBATI", value: "ki" },
  { label: "KOSOVO", value: "xk" },
  { label: "KOREA DEMOCRATIC PEOPLES REPUBLIC OF", value: "kp" },
  { label: "KOREA REPUBLIC OF", value: "kr" },
  { label: "KUWAIT", value: "kw" },
  { label: "NORTH KOREA", value: "kp" },
  { label: "SOUTH KOREA", value: "kr" },
  { label: "KYRGYZSTAN", value: "kg" },
  { label: "LAO PEOPLES DEMOCRATIC REPUBLIC", value: "la" },
  { label: "LATVIA", value: "lv" },
  { label: "LAOS", value: "la" },
  { label: "LEBANON", value: "lb" },
  { label: "LESOTHO", value: "ls" },
  { label: "LIBERIA", value: "lr" },
  { label: "LIBYAN ARAB JAMAHIRIYA", value: "ly" },
  { label: "LIECHTENSTEIN", value: "li" },
  { label: "LIBYA", value: "ly" },
  { label: "LITHUANIA", value: "lt" },
  { label: "LUXEMBOURG", value: "lu" },
  { label: "MACAU", value: "mo" },
  { label: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", value: "mk" },
  { label: "MADAGASCAR", value: "mg" },
  { label: "MACEDONIA", value: "mk" },
  { label: "MALAWI", value: "mw" },
  { label: "MALAYSIA", value: "my" },
  { label: "MALDIVES", value: "mv" },
  { label: "MALI", value: "ml" },
  { label: "MALTA", value: "mt" },
  { label: "MARSHALL ISLANDS", value: "mh" },
  { label: "MARTINIQUE", value: "mq" },
  { label: "MAURITANIA", value: "mr" },
  { label: "MAURITIUS", value: "mu" },
  { label: "MAYOTTE", value: "yt" },
  { label: "MEXICO", value: "mx" },
  { label: "MICRONESIA, FEDERATED STATES OF", value: "fm" },
  { label: "MOLDOVA, REPUBLIC OF", value: "md" },
  { label: "MONACO", value: "mc" },
  { label: "MOLDOVA", value: "md" },
  { label: "MICRONESIA", value: "fm" },
  { label: "MONGOLIA", value: "mn" },
  { label: "MONTSERRAT", value: "ms" },
  { label: "MOROCCO", value: "ma" },
  { label: "MOZAMBIQUE", value: "mz" },
  { label: "MYANMAR", value: "mm" },
  { label: "MONTENEGRO", value: "me" },
  { label: "NAMIBIA", value: "na" },
  { label: "NAURU", value: "nr" },
  { label: "NEPAL", value: "np" },
  { label: "NETHERLAND", value: "nl" },
  { label: "NETHERLANDS ANTILLES", value: "an" },
  { label: "NEW CALEDONIA", value: "nc" },
  { label: "NEW ZEALAND", value: "nz" },
  { label: "NICARAGUA", value: "ni" },
  { label: "NIGER", value: "ne" },
  { label: "NIGERIA", value: "ng" },
  { label: "NIUE", value: "nu" },
  { label: "NORFOLK ISLAND", value: "nf" },
  { label: "NORTHERN MARIANA ISLANDS", value: "mp" },
  { label: "NORWAY", value: "no" },
  { label: "OMAN", value: "om" },
  { label: "PAKISTAN", value: "pk" },
  { label: "PALAU", value: "pw" },
  { label: "PALESTINIAN TERRITORY, OCCUPIED", value: "ps" },
  { label: "PANAMA", value: "pa" },
  { label: "PALESTINE", value: "ps" },
  { label: "PAPUA NEW GUINEA", value: "pg" },
  { label: "PARAGUAY", value: "py" },
  { label: "PERU", value: "pe" },
  { label: "PHILIPPINES", value: "ph" },
  { label: "PITCAIRN", value: "pn" },
  { label: "POLAND", value: "pl" },
  { label: "PORTUGAL", value: "pt" },
  { label: "PUERTO RICO", value: "pr" },
  { label: "QATAR", value: "qa" },
  { label: "REUNION", value: "re" },
  { label: "ROMANIA", value: "ro" },
  { label: "RUSSIAN FEDERATION", value: "ru" },
  { label: "RWANDA", value: "rw" },
  { label: "RUSSIA", value: "ru" },
  { label: "SAINT HELENA", value: "sh" },
  { label: "SAINT KITTS AND NEVIS", value: "kn" },
  { label: "SAINT LUCIA", value: "lc" },
  { label: "SAINT PIERRE AND MIQUELON", value: "pm" },
  { label: "SAINT VINCENT AND THE GRENADINES", value: "vc" },
  { label: "SAMOA", value: "ws" },
  { label: "SAN MARINO", value: "sm" },
  { label: "SAO TOME AND PRINCIPE", value: "st" },
  { label: "SAUDI ARABIA", value: "sa" },
  { label: "SENEGAL", value: "sn" },
  { label: "SEYCHELLES", value: "sc" },
  { label: "SIERRA LEONE", value: "sl" },
  { label: "SINGAPORE", value: "sg" },
  { label: "SLOVAKIA", value: "sk" },
  { label: "SLOVENIA", value: "si" },
  { label: "SOLOMON ISLANDS", value: "sb" },
  { label: "SOMALIA", value: "so" },
  { label: "SOUTH AFRICA", value: "za" },
  { label: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", value: "gs" },
  { label: "SPAIN", value: "es" },
  { label: "SRI LANKA", value: "lk" },
  { label: "SUDAN", value: "sd" },
  { label: "SURINAME", value: "sr" },
  { label: "SVALBARD AND JAN MAYEN", value: "sj" },
  { label: "SWAZILAND", value: "sz" },
  { label: "ESWATINI", value: "sz" },
  { label: "SWEDEN", value: "se" },
  { label: "SWITZERLAND", value: "ch" },
  { label: "SYRIAN ARAB REPUBLIC", value: "sy" },
  { label: "SYRIA", value: "sy" },
  { label: "TAIWAN, PROVINCE OF CHINA", value: "tw" },
  { label: "TAJIKISTAN", value: "tj" },
  { label: "TANZANIA, UNITED REPUBLIC OF", value: "tz" },
  { label: "TANZANIA", value: "tz" },
  { label: "THAILAND", value: "th" },
  { label: "TOGO", value: "tg" },
  { label: "TOKELAU", value: "tk" },
  { label: "TONGA", value: "to" },
  { label: "TAIWAN", value: "tw" },
  { label: "TRINIDAD AND TOBAGO", value: "tt" },
  { label: "TUNISIA", value: "tn" },
  { label: "TURKEY", value: "tr" },
  { label: "TURKMENISTAN", value: "tm" },
  { label: "TURKS AND CAICOS ISLANDS", value: "tc" },
  { label: "TUVALU", value: "tv" },
  { label: "UGANDA", value: "ug" },
  { label: "UKRAINE", value: "ua" },
  { label: "UNITED STATES OF AMERICA", value: "us" },
  { label: "URUGUAY", value: "uy" },
  { label: "UZBEKISTAN", value: "uz" },
  { label: "VANUATU", value: "vu" },
  { label: "VENEZUELA", value: "ve" },
  { label: "VIETNAM", value: "vi" },
  { label: "VIRGIN ISLANDS, BRITISH", value: "vg" },
  { label: "VIRGIN ISLANDS (BRITISH)", value: "vg" },
  { label: "VIRGIN ISLANDS, U.S.", value: "vi" },
  { label: "WALLIS AND FUTUNA", value: "wf" },
  { label: "WESTERN SAHARA", value: "eh" },
  { label: "YEMEN", value: "ye" },
  { label: "YUGOSLAVIA", value: "yu" },
  { label: "ZAMBIA", value: "zm" },
  { label: "ZIMBABWE", value: "zw" },
  { label: "SERBIA", value: "rs" },
  { label: "SAINT MARTIN(DUTCH)", value: "sx" },
];

export const normalizeCountryCode = (input: string | undefined | null) => {
  const normalizedInput = `${input ?? ""}`.trim().toLowerCase();
  if (!normalizedInput) return "";

  const match = countryOptions.find(
    (option) => option.value.toLowerCase() === normalizedInput || option.label.toLowerCase() === normalizedInput
  );

  return match?.value ?? normalizedInput;
};
